Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2020-10, with the labels that each got.

#853 Add XComTacticalInput.uc for modification
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalInput.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#828 Fix stun action points persisting between missions (#824)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: bug-basegame, ready-for-merge

#778 Update risk level on risk chance recalculation (#777)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
Labels: ready-for-merge

#780 Fire event to allow overriding CA risk chances (#779)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
Labels: ready-for-merge

#839 Unprivated XCGSC_Kismet::FindSequenceOp
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameStateContext_Kismet.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: de-private/const, ready-for-merge

#900 Update X2TacticalGameRulesetDataStructures.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRulesetDataStructures.uc
Labels: ready-for-merge

#893 Add an event to override LostSpawnIncreasePerUse (Issue #892)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge

#833 Implements Issue #832
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
Labels: ready-for-merge

#852 Add an event to override XCGS_Unit::HasHeightAdvantageOver
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge

#865 World region mesh hooks
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_WorldRegion.uc
Labels: ready-for-merge

#876 OverrideCanTakeFacilityMission event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIMission_AlienFacility.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#867 UIStaffContainer fix
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIStaffContainer.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#755 Prevent psi zombies from dropping loot (#682)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge
