Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2021-06, with the labels that each got.

#813 Fix covert action report if rewards prevented (#810)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UICovertActionStaffSlot.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
Labels: ready-for-merge

#870 Loading saves hook
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComOnlineEventMgr.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#995 Add event to override squadsize achievement
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AchievementTracker.uc
Labels: enhancement, ready-to-review

#1012 Remove campaign-start listeners once not needed (#971)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameStateContext_StrategyGameRule.uc
Labels: ready-for-merge

#1015 DLC2HL - Reintroduce features
  Components/DLC2CommunityHighlander/DLC2CommunityHighlander/Src/DLC_2/Classes/XComGameState_AlienRulerManager.uc
Labels: ready-for-merge

#1013 Manually clean up Particle System Components spawned into Emitter Pool by X2UnifiedProjectile
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnitNativeBase.uc
Labels: bug-basegame, ready-for-merge

#1021 Include DLC2 Highlander in documentation
  .github/workflows/docs.yml
  .scripts/make_docs.py
  .vscode/tasks.json
  Components/DLC2CommunityHighlander/DLC2CommunityHighlander/Src/DLC_2/Classes/XComGameState_AlienRulerManager.uc
  docs_directories.txt
  docs_src/docs/index.md
Labels: ready-for-merge

#1020 Fix AllTargetStylesNative detection
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTemplate.uc
Labels: ready-to-review

#997 Add event to override X2ReactionFireSequencer::IsReactionFire()
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2ReactionFireSequencer.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge
