Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2021-05, with the labels that each got.

#930 Fix smoke and poison grenade targeting and effects
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplyPoisonToWorld.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplySmokeGrenadeToWorld.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplySmokeToWorld.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_Grenade.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#958 Make TypicalAbility_BuildVisualization get AbilityState and SourceWeapon from VisualizeGameState when possible
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability.uc
Labels: ready-for-merge

#959 Add OverrideWeaponScale event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComUnitPawn.uc
Labels: ready-for-merge

#985 Pull Request for issue #984
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRulesetDataStructures.uc
Labels: ready-for-merge

#983 Allow runtime modification of loc in X2EncyclopediaTemplate
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2EncyclopediaTemplate.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: de-private/const, ready-for-merge

#563 Override xp distribution
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_XpManager.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#929 Allow mods to override starting region link constraints
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_RegionLink.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_WorldRegion.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: enhancement, ready-for-merge

#769 Allow mods to prevent CA completion from counting towards campaign stats
  X2WOTCCommunityHighlander/Src/XComGame/Classes/AnalyticsManager.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#840 KismetGameStateMatinee event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/SeqAct_PlayGameStateMatinee.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#945 Added speech personality config for TLP attitudes
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
Labels: ready-for-merge

#957 Add event to override ability icon color
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
Labels: ready-for-merge

#784 New DLC hook ModifyGeneratedUnitAppearance
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Reaper.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Skirmisher.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Templar.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#941 Changes to item upgrade system (reupload)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UILadderUpgradeScreen.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIUtilities_Strategy.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AchievementTracker.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2ItemTemplate.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_LadderProgress.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#914 Fix Stocks and Laser Sights not benefitting from empowered upgrades (Issue #896)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplyWeaponDamage.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_LaserSight.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: bug-basegame, ready-for-merge

#965 Rework mod dependency checking
  CHANGELOG.md
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_DialogCallbackData.uc
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_ModDependencies.uc
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_UIScreenListener_ShellPopup.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHModDependency.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
Labels: ready-for-merge

#966 Rework CHL Run Order
  CHANGELOG.md
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.int
  X2WOTCCommunityHighlander/Localization/XComGame.int
  X2WOTCCommunityHighlander/Src/Core/Classes/Object.uc
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2DownloadableContentInfo_X2WOTCCommunityHighlander.uc
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_DialogCallbackData.uc
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_UIScreenListener_ShellPopup.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHDLCInfoTopologicalOrderNode.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHDLCRunOrder.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHDLCRunOrderDiagnostic.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHOnlineEventMgr.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XLocalizedData.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge
