Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2021-07, with the labels that each got.

#925 Add extra damage modifier hooks for effects (#923)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplyWeaponDamage.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Persistent.uc
Labels: ready-to-review

#1002 Add localization for required/incompatible mods popup
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.chn
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.cht
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.deu
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.esn
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.fra
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.ita
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.jpn
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.kor
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.pol
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.rus
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-to-review

#1032 Fix moving melee hangs
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Ability.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityToHitCalc_StandardAim.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: bug-highlander, ready-to-review

#1043 Fix some identified performance issues
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_SoldierInfo.uc
Labels: ready-for-merge

#1041 Add straightforward introduction to run order popups
  X2WOTCCommunityHighlander/Localization/X2WOTCCommunityHighlander.int
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_UIScreenListener_ShellPopup.uc
Labels: ready-for-merge
