Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2021-02, with the labels that each got.

#856 Override camera rotation angle
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_AbilityContainer.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComTacticalInput.uc
Labels: ready-for-merge

#906 Fix weapon models not rotating when previewing weapon upgrades (Issue #39)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponUpgrade.uc
Labels: bug-basegame, ready-for-merge

#910 Add 'none' checks and other fixes to prevent log spam added by TLP (Issue #295)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIImageChip.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UILadderUpgradeScreen.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIPersonnel_SoldierListItem.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITLE_ChallengeModeMenu.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITLE_SkirmishModeMenu.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Enemies.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Action.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyElement_DefaultStaffSlots.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_LadderProgress.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGWeapon.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: bug-basegame, ready-to-review

#926 Fix psi ability selection (#924)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIChoosePsiAbility.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#934 Fix map item select after mission cancel
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_GeoscapeEntity.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#928 Support campaign-start event listeners (#297)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHEventListenerTemplate.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2EventListenerTemplateManager.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameStateContext_StrategyGameRule.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: enhancement, ready-for-merge

#938 Add inline docs for multiple issues
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_LoadoutItem.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_AbilityContainer.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2CovertActionTemplate.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_PersistentStatChange.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2SitRepTemplate.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2SoldierClassTemplateManager.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_RocketLauncher.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIGroup.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_AIReinforcementSpawner.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersProjectPsiTraining.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersProjectRespecSoldier.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersResistance.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_InteractiveObject.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHumanPawn.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
Labels: ready-for-merge

#935 Allow mods to update strategy-map nav help (#932)
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIStrategyMap.uc
Labels: ready-for-merge

#942 Add UISquadSelect_NavHelpUpdate Event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UISquadSelect.uc
Labels: ready-for-merge

#738 Small improvements to #621 and #595 for 1.20.0 beta
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIScreenStack.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_ResistanceFaction.uc
Labels: ready-for-merge

#963 Make OverrideItemImage pass on Item State
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_LoadoutItem.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
Labels: ready-for-merge

#956 Add OverrideDamageRemovesOverwatch event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge

#950 Extend HasHeavyWeapon() check
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge

#918 Custom ability target styles v2
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTemplate.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Ability.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Ability_CH.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-to-review

#946 Bleeding through shields
  X2WOTCCommunityHighlander/Config/XComGameCore.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StatusEffects.uc
Labels: ready-to-review

#907 Unhide the weapon pattern customization screen
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_WeaponTrait.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-to-review

#939 Reimplement issue #694
  CHANGELOG.md
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge

#937 Add unused WillEventRollStat_Flat - Issue #936
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameStateContext_WillRoll.uc
Labels: ready-to-review

#948 Add PostInventoryLoadoutApplied event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge
