Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2022-02, with the labels that each got.

#1117 Add 'OverrideMetaHitEffect' event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComUnitPawn.uc
Labels: ready-to-review

#1115 Update docs and functionality for OverrideHitEffects event
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComUnitPawn.uc
Labels: ready-to-review

#1119 Fix importing single characters from certain Character Pools silently failing
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UICharacterPool_ListPools.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: bug-basegame, ready-to-review

#1106 Issue #1084 - Allow choosing target tile for meleeing adjacent targets
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2MeleePathingPawn.uc
Labels: ready-to-review

#1105 Add eInvSlot_ entries for modular sparks.
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRulesetDataStructures.uc
Labels: ready-for-merge

#1103 Resolves #1101
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
Labels: ready-for-merge

#1100 Add a different trunctuation method to damage modifier hooks
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplyWeaponDamage.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Persistent.uc
Labels: ready-for-merge

#1122 Make GetUISummary_UnitStatusIcons() skip empty status icons
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: bug-basegame, ready-to-review
