Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2023-08, with the labels that each got.

#1216 Prevent hit modifiers from applying to indirect fire
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityToHitCalc_StandardAim.uc
Labels: bug-basegame, ready-to-review, ready-for-merge

#1230 Update X2TacticalGameRulesetDataStructures.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRulesetDataStructures.uc
Labels: ready-for-merge

#1194 IsIncapacitated check to GatherUnitsToMove #1193
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGAIPlayer.uc
Labels: bug-basegame, ready-for-merge

#1202 Issue #917 - Update EndTacticalHealthMod() in XCGS_Unit to expose beta strike post mission healing to config
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: enhancement, ready-for-merge

#1001 Some docs fixes
  .scripts/make_docs.py
  CHANGELOG.md
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHDLCRunOrder.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHModDependency.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UICovertActionStaffSlot.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TargetingMethod_Grenade.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
Labels: ready-to-review

#1225 XEXPAND Chosen Abilities - Additional files
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIChosenLevelUp.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIChosenReveal.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: ready-for-merge

#1207 Add MarkPlotUsed call for missions that don't use the dropship
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
Labels: bug-basegame, ready-for-merge

#1197 Fix Return Fire not working if the enemy is in high cover
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_DefaultAbilitySet.uc
Labels: bug-basegame, ready-to-review

#1214 Make Return Fire visualize after Covering Fire Overwatch
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_DefaultAbilitySet.uc
Labels: bug-basegame, ready-to-review

#1227 Fix units using the wrong weapon when interrupted
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Action_ApplyWeaponDamageToUnit.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnitNativeBase.uc
Labels: bug-basegame, ready-to-review

#1203 Stop sounds when removing pawns
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIPawnMgr.uc
Labels: bug-basegame, ready-to-review

#1238 Make Dodge apply to Hit and Crit equally
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityToHitCalc.uc
Labels: bug-basegame, ready-to-review

#1169 Add option to send sound alerts data to allies
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: enhancement, ready-for-merge

#1244 Destroy cosmetic pawns when items are unequipped
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIPawnMgr.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: bug-basegame, ready-for-merge
