Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2023-05, with the labels that each got.

#1170 Fix editing covert action soldier loadouts with a controller
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UICovertActions.uc
Labels: bug-basegame, ready-for-merge

#1151 Allow mods to Override Rolling for negative traits
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: ready-for-merge

#1149 Create an option to make Fatigue and Injury Times Independent
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameStateContext_HeadquartersOrder.uc
Labels: ready-for-merge

#1132 Fix Homing Mine always applying bonus environmental damage from Shrapnel
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_ReaperAbilitySet.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_HomingMineDamage.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: bug-basegame, ready-to-review

#1141 Issue #1140 - fix bugs introduced by Issue #783
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Reaper.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Skirmisher.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Templar.uc
Labels: bug-highlander

#1167 Prevent built-in hit and crit modifiers from applying against non-units
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityToHitCalc_StandardAim.uc
Labels: bug-basegame, ready-to-review

#1173 Add an event to localize new Item Categories
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2ItemTemplate.uc
Labels: enhancement, ready-to-review

#1175 Make GetPCSRanks() use soldier's own soldier class template
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: bug-basegame, ready-to-review

#1176 Call OverrideItemImage_Improved from the Item State
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIArmory_LoadoutItem.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
Labels: enhancement, ready-to-review

#1179 Fix TriggerOverrideProjectileInstance()
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnitNativeBase.uc
Labels: bug-highlander, ready-to-review

#1186 Implement Issue #1140 - fix bugs in #783 and update docs
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Reaper.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Skirmisher.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator_Templar.uc
Labels: bug-highlander

#1185 Reset version numbers in Highlander code
  X2WOTCCommunityHighlander/Src/Core/Classes/CHCoreVersion.uc
  X2WOTCCommunityHighlander/Src/Engine/Classes/CHEngineVersion.uc
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/CHX2WOTCCHVersion.uc
  X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_CHXComGameVersion.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHXComGameVersionTemplate.uc
Labels: bug-highlander
