Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2024-12, with the labels that each got.

#1415 Fix bugs with Revival Protocol and Restoration
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_SpecialistAbilitySet.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_RevivalProtocol.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_RevivalProtocolRestoreAP.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: bug-basegame

#1424 Issue #559 - Add eCleanup_BeginTacticalChain
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Sustain.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Item_DefaultUpgrades.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRulesetDataStructures.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc
Labels: bug-basegame, ready-for-merge

#1423 Fix for loading screen hang when bSkipCampaignIntroMovies = true in CHHelpers
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIShellDifficulty.uc
Labels: bug-highlander, ready-for-merge

#1422 Add a check if a WWise voiceline exists to prevent attempts to play missing voicelines
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
Labels: bug-basegame, ready-for-merge

#1421 Adjust voiceline checks in X2Action_ApplyWeaponDamageToUnit and add a delay to the 'SquadMemberDead' voiceline
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Action_ApplyWeaponDamageToUnit.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc
Labels: bug-basegame, ready-for-merge

#1407 Add a new event trigger after Mission Intro kismet has completed
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
Labels: ready-for-merge

#1403 Docs - Photobooth Enums
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Photobooth.uc
Labels: docs, ready-for-merge

#1351 Properly trigger unit concealment loss when bForceNoSquadConcealment flag is set instead of not concealing in the first place.
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc
Labels: bug-basegame, ready-for-merge
