Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2024-11, with the labels that each got.

#1387 Cache hit chance when sorting the list of potential targets in tactical and ensure the sorted order matches the order of TAB-cycling
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UITacticalHUD_Enemies.uc
Labels: enhancement, ready-to-review

#1402 Docs - Parts validation on Torso Change
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComCharacterCustomization.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XGCharacterGenerator.uc
Labels: needs-docs, ready-for-merge

#1362 Updated OnUnitDied to properly kill gremlins when their owner dies
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc
Labels: bug-basegame, ready-to-review

#1367 Add docs - Gremlin customization
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComCharacterCustomization.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComUnitPawn.uc
Labels: docs, ready-for-merge

#1401 Allow forcing 24h clock and leading zeroes on month and date strings
  X2WOTCCommunityHighlander/Config/XComGameData.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
Labels: enhancement, ready-for-merge

#1413 Fix PR1401 - Issue with native variable declaration
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Config/XComGameData.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2StrategyGameRulesetDataStructures.uc
Labels: bug-highlander, ready-to-review

#1212 Implement Better Positive Trait UI
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAlert.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAvengerHud_SoldierStatusIndicatorContainer.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
Labels: enhancement, ready-to-review

#1388 Prevent Low Intel warnings if all regions are contacted
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIUtilities_Strategy.uc
Labels: bug-basegame
