Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2024-05, with the labels that each got.

#1327 Add eInv Slots to enable Soldiers to carry multiple unique Proximity-Activated Items for the Requiem Campaign
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRulesetDataStructures.uc
Labels: ready-for-merge

#1321 Allow hit results other than `eHit_Success` to display flyovers when using bCombineFlyovers
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Action_ApplyWeaponDamageToUnit.uc
Labels: bug-basegame, ready-to-review

#1330 Remove cap from bonus damage added by rupture and make rupture apply after attack's damage
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplyWeaponDamage.uc
Labels: bug-basegame

#1335 Use Typical Weapon Action Cost for Banish and Sting
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_ReaperAbilitySet.uc
Labels: bug-basegame

#1338 Allow abilities that are supposed to always crit to crit if aim assist converts their miss into a hit
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityToHitCalc_StandardAim.uc
Labels: bug-basegame

#1339 Make guaranteed crit abilities display as having 100% crit chance
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityToHitCalc_StandardAim.uc
Labels: bug-basegame

#1340 Separate and localize Defense stat modifiers
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityToHitCalc_StandardAim.uc
Labels: enhancement

#1344 Prevent rupture bonus damage from being added to attack that don't deal damage
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplyWeaponDamage.uc
Labels: bug-highlander
