Repository X2CommunityCore/X2WOTCCommunityHighlander, pull requests merged in 2025-06, with the labels that each got.

#1443 Add check for Tick context to eHit_Crit and eHit-Graze
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_ApplyWeaponDamage.uc
Labels: bug-basegame, ready-for-merge

#1454 Config gate creation of auto-generated photos (#1453)
  X2WOTCCommunityHighlander/Config/XComGame.ini
  X2WOTCCommunityHighlander/Src/XComGame/Classes/CHHelpers.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAfterAction.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UIMissionSummary.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/UISoldierBondConfirmScreen.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHQPresentationLayer.uc
Labels: enhancement, ready-for-merge

#1440 Restoration Targeting Fix
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Ability_SpecialistAbilitySet.uc
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Condition_Restoration.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: bug-basegame, ready-for-merge

#1448 Fix for erroneous burst-fire effect stacking
  X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Effect.uc
Labels: bug-basegame, ready-to-review

#1437 Add bunch of knockback fixes
  X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Knockback.uc
  X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj
Labels: bug-basegame, waiting-on-author
